# Generated by Django 4.0.3 on 2022-08-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couchr_lists', '0002_remove_list_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movievo',
            name='picture_url',
        ),
    ]
