# Generated by Django 4.0.3 on 2022-09-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couchr_lists', '0003_wishlist_watchedlist_likedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movievo',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
