# Generated by Django 4.0.3 on 2022-08-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couchr_lists', '0003_remove_movievo_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movievo',
            name='api_url',
        ),
        migrations.AddField(
            model_name='movievo',
            name='movie_api_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
