# Generated by Django 4.0.3 on 2022-08-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couchr_lists', '0004_remove_movievo_api_url_movievo_movie_api_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movievo',
            old_name='movie_api_id',
            new_name='api_id',
        ),
        migrations.AddField(
            model_name='movievo',
            name='api_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
