# Generated by Django 4.0.3 on 2022-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couchr_lists', '0004_movievo_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movievo',
            name='release_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movievo',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
