# Generated by Django 4.0.3 on 2022-08-31 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couchr_lists', '0005_rename_movie_api_id_movievo_api_id_movievo_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
