# Generated by Django 4.0.3 on 2022-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couchr_lists', '0006_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='couchr_lists.movievo'),
        ),
    ]
