# Generated by Django 4.0.3 on 2022-08-31 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couchr_lists', '0008_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(blank=True, to='couchr_lists.movievo'),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
